version: 1.0.{build}
configuration: Release
platform: x64
install:
- cmd: "git submodule update --init spec\nappveyor DownloadFile -Url https://github.com/innative-sdk/llvm-project/releases/download/v10.0.0-innative/llvm-10.0.0-x86-64-windows.zip  \n7z x llvm-10.0.0-x86-64-windows.zip\nmkdir .\\bin\\llvm\\bin\nmkdir .\\bin\\llvm\\include\nmkdir .\\bin\\llvm\\lib\nxcopy .\\llvm-10.0.0-x86-64-windows\\bin\\* .\\bin\\llvm\\bin\\ /E\nxcopy .\\llvm-10.0.0-x86-64-windows\\include\\* .\\bin\\llvm\\include\\ /E\nxcopy .\\llvm-10.0.0-x86-64-windows\\lib\\* .\\bin\\llvm\\lib\\ /E"
build:
  project: innative.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd bin

    innative-test.exe -auto -ignore=17

    cd ..